address: ":8080"
log_level: "info"
storage: "postgres" # "in-memory" или "postgres"
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "myUser"
  password: "12345"
  name: "myDb"
  sslmode: "disable"
