address: ":8080"
log_level: "info"
storage: "in-memory" # "in-memory" или "postgres"
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  name: "mydb"
  sslmode: "disable"
