version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: myDb
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=config.yaml
